name: Build
on:
  pull_request:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm run build
