name: HACS validation
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "plugin"
